### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'token')    

### ISSUE THREAD

**Issue by madhavSoni** [rye-com/rye-pay#32]
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'token')
    at RyePay.getEnvToken (rye-pay.js:333:1)
    at async script.onload (rye-pay.js:163:1)


async function initRyePay() {
            if (cartID) {
                const ryePay = new RyePay();
                const response = await API.generateJWTToken();
                console.log(response.token);
                const token = response.token;
                ryePay.init({
                    generateJWT: () => {
                        return token;
                    },
                    numberEl: 'spreedly-number',
                    cvvEl: 'spreedly-cvv',
                    environment: 'stage',
                    onReady: () => {
                        console.log('rye pay is ready');
                        // Customize card numbeRyePay is readyr field and CVV field
                        ryePay.setStyle(
                            'number',
                            'display:inline; width: 30%; border-radius: 3px; border: 1px solid #ccc; height: 50px;',
                        );
                        ryePay.setStyle(
                            'cvv',
                            'display: inline; width: 30%; border-radius: 3px; border: 1px solid #ccc;',
                        );
                    },
                    enableLogging: true,
                    onErrors: (errors: any) => {
                        for (const { key, message, attribute } of errors) {
                            console.log(`new error: ${key}-${message}-${attribute}`);
                        }
                    },
                    onIFrameError: (error: any) => {
                        console.log(`IFrame error: ${error}`);
                    }
                });
                console.log("res ", ryePay);
                ryePayRef.current = ryePay;
                console.log("REF: ", ryePayRef.current);
            }
        }
        initRyePay();
        getCartInfo();
    }, [cartID]);
```
Before initializing the Rye Pay library, we can successfully retrieve the JWT Token from our backend (We tested this with both STAGING and PROD keys/environments), but we are unable to properly initialize the library. We continually get the error and have not been able to find a resolution. We followed the guide by savings the key in the developer portal on rye and going through the steps.

**Comment by madhavSoni** [comment]
While the token is formatted and returned correctly from our backend, we continually get the above error

**Comment by sophiabits** [comment]
Hey @madhavSoni thanks for reporting this. I can reproduce this error if I return an invalid JWT from `generateJWT`, but can't reproduce this with a valid JWT.

You can verify whether the JWT is valid or not by making an API call manually, e.g.:

```
await fetch('https://staging.beta.graphql.api.rye.com/v1/query', {
  method: 'POST',
  headers: {
    Authorization: `Bearer ${token}`,
    'Content-Type': 'appliction/json',
  },
  body: JSON.stringify({
    query: `
      query {
        environmentToken {
          token
        }
      }
    `,
  }),
});
```

If that call fails, it means the JWT is invalid. Let me know how you get on.

**Comment by cnowdev** [comment]
Hi @sophiabits! Thank you so much for helping us figure out this error.

I tried the following just like your example:

```js 
useEffect(() => {


        async function test(){
            API.generateJWTToken().then((token) => {
            console.log(token);
            fetch('https://staging.beta.graphql.api.rye.com/v1/query', {
                method: 'POST',
                headers: {
                  'Content-Type': 'application/json',
                  'Authorization': `Bearer ${token}`
                },
                body: JSON.stringify({
                  query: `
                    query {
                      environmentToken {
                        token
                      }
                    }
                  `,
                }),
              });
            });
        }

        test();

       
    }, []);
```

This call is failing, with this response:
![image](https://github.com/rye-com/rye-pay/assets/34350791/f6db5bf4-1694-44ea-97c0-01df7ea1bf56)

Could you take a look at our backend implementation for the `generateJWTToken()` function? Please do let us know if we are doing something wrong here. I've ensured that the audience is set to "staging.graphql.api.rye.com" and that the issuer is the one from the console.

```
const RSA_PRIVATE_KEY = fs.readFileSync(path.resolve(__dirname, 'private_key.pem'), 'utf8');
console.log(RSA_PRIVATE_KEY);

export default class AuthService {
  public generateJWTToken(): string {
    return jwt.sign(
      {},
      RSA_PRIVATE_KEY, //Private key to sign the token
      {
        algorithm: 'RS256',
        expiresIn: '1h',
        audience: process.env.JWT_AUDIENCE,
        issuer: process.env.JWT_ISSUER,
      }
    );
  }
}
```

**Comment by AnikDey-exe** [comment]
Judging by the response I'm getting I think the JWT token generated from our endpoint is working and valid.

**Comment by AnikDey-exe** [comment]
Ok I think it works when using hardcoded JWTs

**Comment by AnikDey-exe** [comment]
But I don't know why it doesn't work using the endpoint.

**Comment by cnowdev** [comment]
It works when setting a 5 second delay between generating the token and returning the token! I'm not sure why this works, and I feel like there has to be a better solution to the problem though.

**Comment by sophiabits** [comment]
Ah okay. It could be a clock skew issue. We validate that the expiration time of the JWT is not more than 1 hour in the future, so if your system clock is a few seconds ahead of where it should be then that would cause the issue you are seeing.

We have a ticket on our backlog for making the developer experience in this case better. In the meantime, can you resync your clock? If you are working locally on macOS, then you can untick + retick "Set time and date automatically" in system settings to do this

**Comment by AnikDey-exe** [comment]
@sophiabits You are right, I synced my clock and it seemed to fix it. However, is there a solution to this issue because some users' clocks may not be synced?

**Comment by sophiabits** [comment]
Awesome :) Glad to hear that that resolved the issue for you

This is unlikely to be an issue in production. The clock that matters here is the one on your backend; so long as that one is correct you will not have a problem. If you're deploying your application on a public cloud then the date & time will be good by default.

Otherwise you could work around this by reducing the TTL of the jwt. e.g. instead of issuing it for 1 hour, issue it for 59 minutes. This would give you a 1 minute allowance for clock skew.
